# Generated by Django 2.1.7 on 2019-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190223_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_lastUpdated',
            field=models.DateTimeField(),
        ),
    ]
