# Generated by Django 2.1.7 on 2019-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default='2020-01-01'),
        ),
    ]
