# Generated by Django 2.1.7 on 2019-02-24 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
