# Generated by Django 2.1.5 on 2019-02-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('timestamp_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='TestResultLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(max_length=50)),
                ('documnetId', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('linetype', models.CharField(max_length=10)),
                ('lineNbr', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=20)),
                ('actualResult', models.CharField(max_length=255)),
                ('expectedResult', models.CharField(max_length=255)),
                ('verify', models.CharField(max_length=50)),
                ('runId', models.CharField(max_length=20)),
                ('testSuite', models.CharField(max_length=50)),
                ('testCase', models.CharField(max_length=50)),
                ('tester', models.CharField(max_length=50)),
                ('environment', models.CharField(max_length=10)),
                ('additionalComment', models.CharField(max_length=100)),
                ('userStory', models.CharField(max_length=100)),
                ('accpetanceCriteria', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
