# Generated by Django 2.1.5 on 2019-02-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResultLog',
            new_name='Test_Result_Log',
        ),
    ]
