# Generated by Django 2.1.5 on 2019-02-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190215_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactEntry',
            new_name='Contact',
        ),
    ]
