# Generated by Django 2.1.5 on 2019-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_test_result_log_jira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result_log',
            name='verify',
            field=models.CharField(max_length=100),
        ),
    ]
