# Generated by Django 2.1.5 on 2019-02-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20190216_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='full_nmae',
            new_name='full_name',
        ),
    ]
