# Generated by Django 2.1.7 on 2019-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
            ],
        ),
    ]
